export interface SearchItem {
  title: string;
  description: string;
  href: string;
  category: string;
  keywords: string[];
}

export const searchData: SearchItem[] = [
  {
    title: "Introduction",
    description: "Welcome to the Apex documentation. This utility-first framework provides a comprehensive set of CSS classes for rapid UI development.",
    href: "/",
    category: "Getting Started",
    keywords: ["introduction", "getting started", "overview", "welcome"],
  },
  {
    title: "Getting Started",
    description: "Learn how to get started with Apex in your project via CDN or NPM.",
    href: "/getting-started/",
    category: "Getting Started",
    keywords: ["install", "setup", "quick start", "cdn", "npm"],
  },
  {
    title: "Design System",
    description: "Apex provides a comprehensive design system with consistent colors, typography, spacing, and more.",
    href: "/design-system/",
    category: "Design System",
    keywords: ["colors", "typography", "spacing", "shadows", "design tokens"],
  },
  {
    title: "Customization",
    description: "Tailor Apex to match your brand and project requirements.",
    href: "/customization/",
    category: "Design System",
    keywords: ["customize", "branding", "theme", "css variables"],
  },
  {
    title: "Utilities",
    description: "Utility classes for spacing, typography, colors, flexbox, grid, and more.",
    href: "/utilities/",
    category: "Core Concepts",
    keywords: ["utilities", "helpers", "classes"],
  },
  {
    title: "Components",
    description: "Pre-built components for common UI patterns including buttons, cards, forms, and more.",
    href: "/components/",
    category: "Core Concepts",
    keywords: ["components", "ui", "elements", "widgets"],
  },
  {
    title: "Responsive Design",
    description: "Build responsive layouts with Apex utility classes and breakpoints.",
    href: "/responsive-design/",
    category: "Core Concepts",
    keywords: ["responsive", "mobile", "breakpoints", "media queries"],
  },
  {
    title: "Dark Mode",
    description: "Apex provides built-in dark mode support with automatic switching.",
    href: "/dark-mode/",
    category: "Core Concepts",
    keywords: ["dark", "theme", "night mode", "auto"],
  },
  {
    title: "API Reference",
    description: "Complete reference for Apex classes and utilities.",
    href: "/api-reference/",
    category: "Reference",
    keywords: ["api", "reference", "documentation", "classes"],
  },
  {
    title: "Browser Support",
    description: "Apex supports all modern browsers including Chrome, Firefox, Safari, and Edge.",
    href: "/browser-support/",
    category: "Reference",
    keywords: ["browser", "support", "compatibility", "can i use"],
  },
  {
    title: "Migration Guides",
    description: "Step-by-step guides for migrating from other CSS frameworks to Apex.",
    href: "/migration/",
    category: "Migration",
    keywords: ["migration", "migrate", "switch", "convert"],
  },
  {
    title: "From Tailwind CSS",
    description: "Migrate your project from Tailwind CSS to Apex.",
    href: "/migration/from-tailwind/",
    category: "Migration",
    keywords: ["tailwind", "migration", "convert"],
  },
  {
    title: "From Bootstrap",
    description: "Migrate your project from Bootstrap to Apex.",
    href: "/migration/from-bootstrap/",
    category: "Migration",
    keywords: ["bootstrap", "migration", "convert"],
  },
  {
    title: "From Bulma",
    description: "Migrate your project from Bulma to Apex.",
    href: "/migration/from-bulma/",
    category: "Migration",
    keywords: ["bulma", "migration", "convert"],
  },
  {
    title: "Plugin Development",
    description: "Extend Apex with custom plugins.",
    href: "/plugins/",
    category: "Advanced",
    keywords: ["plugin", "extension", "custom", "api"],
  },
  {
    title: "Performance",
    description: "Best practices for optimal performance with Apex.",
    href: "/performance/",
    category: "Advanced",
    keywords: ["performance", "optimization", "bundle", "size"],
  },
  {
    title: "Accessibility",
    description: "Apex prioritizes accessibility with built-in support for screen readers, focus management, and keyboard navigation.",
    href: "/accessibility/",
    category: "Advanced",
    keywords: ["accessibility", "a11y", "aria", "screen reader", "wcag"],
  },
  {
    title: "RTL Support",
    description: "Apex includes built-in RTL (Right-to-Left) support for internationalization.",
    href: "/rtl/",
    category: "Advanced",
    keywords: ["rtl", "right to left", "internationalization", "i18n", "arabic", "hebrew"],
  },
  {
    title: "Troubleshooting",
    description: "Common issues and how to resolve them.",
    href: "/troubleshooting/",
    category: "Help",
    keywords: ["troubleshoot", "error", "issue", "problem", "fix"],
  },
  {
    title: "FAQ",
    description: "Frequently asked questions about Apex.",
    href: "/faq/",
    category: "Help",
    keywords: ["faq", "question", "answer", "common"],
  },
  {
    title: "Community",
    description: "Join the Apex community and connect with other developers.",
    href: "/community/",
    category: "Community",
    keywords: ["community", "discord", "github", "twitter"],
  },
  {
    title: "Contributing",
    description: "Thank you for your interest in contributing to Apex!",
    href: "/contributing/",
    category: "Community",
    keywords: ["contribute", "contribution", "developer", "open source"],
  },
  {
    title: "Changelog",
    description: "Release history and changes.",
    href: "/changelog/",
    category: "Community",
    keywords: ["changelog", "release", "version", "history"],
  },
  {
    title: "Playground",
    description: "Try Apex utilities directly in your browser.",
    href: "/playground/",
    category: "Tools",
    keywords: ["playground", "demo", "try", "experiment"],
  },
  {
    title: "Configuration",
    description: "Customize Apex to fit your project needs.",
    href: "/configuration/",
    category: "Tools",
    keywords: ["configuration", "config", "settings", "customize"],
  },
  // Additional utility keywords
  {
    title: "Spacing Utilities",
    description: "Margin and padding utilities for controlling space.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["spacing", "margin", "padding", "m-", "p-", "space"],
  },
  {
    title: "Typography Utilities",
    description: "Text and font utilities for styling typography.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["typography", "text", "font", "size", "weight", "color"],
  },
  {
    title: "Color Utilities",
    description: "Background and text color utilities.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["color", "bg-", "text-", "background", "palette"],
  },
  {
    title: "Flexbox Utilities",
    description: "Flexbox layout utilities for creating flexible layouts.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["flexbox", "flex", "layout", "align", "justify"],
  },
  {
    title: "Grid Utilities",
    description: "Grid layout utilities for creating grid-based layouts.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["grid", "grid-cols", "gap", "columns"],
  },
  {
    title: "Border Utilities",
    description: "Border utilities for controlling borders.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["border", "rounded", "radius", "outline"],
  },
  {
    title: "Sizing Utilities",
    description: "Width and height utilities.",
    href: "/utilities/",
    category: "Utilities",
    keywords: ["sizing", "width", "height", "w-", "h-", "size"],
  },
];
